/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: 'Instagram media id from Bright Data',
          hidden: false,
          id: 'text3911028471',
          max: 64,
          min: 1,
          name: 'instagramId',
          pattern: '',
          presentable: true,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          exceptDomains: null,
          help: '',
          hidden: false,
          id: 'url3500432199',
          name: 'permalink',
          onlyDomains: null,
          presentable: false,
          required: true,
          system: false,
          type: 'url',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text2648555711',
          max: 2200,
          min: 0,
          name: 'caption',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          help: '',
          hidden: false,
          id: 'date4149654991',
          max: '',
          min: '',
          name: 'postedAt',
          presentable: false,
          required: false,
          system: false,
          type: 'date',
        },
        {
          help: '',
          hidden: false,
          id: 'select3262944111',
          maxSelect: 1,
          name: 'mediaType',
          presentable: false,
          required: false,
          system: false,
          type: 'select',
          values: ['image', 'video', 'carousel'],
        },
        {
          hidden: false,
          id: 'file2359244399',
          maxSelect: 1,
          maxSize: 10485760,
          mimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
          name: 'image',
          presentable: true,
          protected: false,
          required: false,
          system: false,
          thumbs: ['400x400'],
          type: 'file',
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      id: 'pbc_3911028471',
      indexes: ['CREATE UNIQUE INDEX `idx_instagram_post_instagramId` ON `instagram_post` (`instagramId`)'],
      listRule: '',
      name: 'instagram_post',
      system: false,
      type: 'base',
      updateRule: null,
      viewRule: '',
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_3911028471')

    return app.delete(collection)
  },
)
