/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text2144962859',
          max: 0,
          min: 0,
          name: 'label_en',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text4030710865',
          max: 0,
          min: 0,
          name: 'label_ru',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text801197831',
          max: 0,
          min: 0,
          name: 'label_uz',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          exceptDomains: null,
          help: '',
          hidden: false,
          id: 'url4101391790',
          name: 'url',
          onlyDomains: null,
          presentable: false,
          required: false,
          system: false,
          type: 'url',
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      id: 'pbc_1382429780',
      indexes: [],
      listRule: null,
      name: '_button',
      system: false,
      type: 'base',
      updateRule: null,
      viewRule: null,
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_1382429780')

    return app.delete(collection)
  },
)
