/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_3555510918',
          help: '',
          hidden: false,
          id: 'relation1586093754',
          maxSelect: 0,
          minSelect: 0,
          name: 'play',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          help: '',
          hidden: false,
          id: 'date3075695607',
          max: '',
          min: '',
          name: 'start_at',
          presentable: false,
          required: false,
          system: false,
          type: 'date',
        },
        {
          exceptDomains: null,
          help: '',
          hidden: false,
          id: 'url3986445568',
          name: 'ticket_purchase_url',
          onlyDomains: null,
          presentable: false,
          required: false,
          system: false,
          type: 'url',
        },
        {
          help: '',
          hidden: false,
          id: 'number3838560732',
          max: null,
          min: null,
          name: 'price_uzs',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      id: 'pbc_1001558001',
      indexes: [],
      listRule: null,
      name: 't_performance',
      system: false,
      type: 'base',
      updateRule: null,
      viewRule: null,
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_1001558001')

    return app.delete(collection)
  },
)
