/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_829252413',
          help: '',
          hidden: false,
          id: 'relation3334677187',
          maxSelect: 10,
          minSelect: 0,
          name: 'cashier_phone',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_829252413',
          help: '',
          hidden: false,
          id: 'relation4212367759',
          maxSelect: 10,
          minSelect: 0,
          name: 'administration_phone',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          exceptDomains: null,
          help: '',
          hidden: false,
          id: 'url1858974015',
          name: 'youtube_url',
          onlyDomains: null,
          presentable: false,
          required: false,
          system: false,
          type: 'url',
        },
        {
          exceptDomains: null,
          help: '',
          hidden: false,
          id: 'url260122942',
          name: 'instagram_url',
          onlyDomains: null,
          presentable: false,
          required: false,
          system: false,
          type: 'url',
        },
        {
          exceptDomains: null,
          help: '',
          hidden: false,
          id: 'url1002431072',
          name: 'telegram_url',
          onlyDomains: null,
          presentable: false,
          required: false,
          system: false,
          type: 'url',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text3401084027',
          max: 0,
          min: 0,
          name: 'contact_email',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          exceptDomains: null,
          help: '',
          hidden: false,
          id: 'url706829292',
          name: 'google_maps_url',
          onlyDomains: null,
          presentable: false,
          required: false,
          system: false,
          type: 'url',
        },
        {
          exceptDomains: null,
          help: '',
          hidden: false,
          id: 'url1270789886',
          name: 'yandex_maps_url',
          onlyDomains: null,
          presentable: false,
          required: false,
          system: false,
          type: 'url',
        },
        {
          help: '',
          hidden: false,
          id: 'file2287213166',
          maxSelect: 0,
          maxSize: 0,
          mimeTypes: null,
          name: 'map_dark',
          presentable: false,
          protected: false,
          required: false,
          system: false,
          thumbs: null,
          type: 'file',
        },
        {
          help: '',
          hidden: false,
          id: 'file3958117275',
          maxSelect: 0,
          maxSize: 0,
          mimeTypes: null,
          name: 'map_light',
          presentable: false,
          protected: false,
          required: false,
          system: false,
          thumbs: null,
          type: 'file',
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      id: 'pbc_1919269059',
      indexes: [],
      listRule: null,
      name: 't_contact',
      system: false,
      type: 'base',
      updateRule: null,
      viewRule: null,
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_1919269059')

    return app.delete(collection)
  },
)
