/// <reference path="../pb_data/types.d.ts" />

migrate(
  (app) => {
    const posts = [
      {
        slug: 'tashkent-flowers-fest-2026',
        published_at: '2026-05-10 09:00:00.000Z',
        published: true,
        sample: false,
        cover_width: 1290,
        cover_height: 2284,
        cover_url: 'https://teatrplus.uz/wp-content/uploads/2026/07/festival-1.jpg',
        gallery_urls: [
          'https://teatrplus.uz/wp-content/uploads/2026/07/festival-1.jpg',
          'https://teatrplus.uz/wp-content/uploads/2026/07/festival-6.jpg',
          'https://teatrplus.uz/wp-content/uploads/2026/07/festival-5.jpg',
          'https://teatrplus.uz/wp-content/uploads/2026/07/festival-4.jpg',
          'https://teatrplus.uz/wp-content/uploads/2026/07/festival-3.jpg',
          'https://teatrplus.uz/wp-content/uploads/2026/07/festival-2.jpg',
        ],
        title_ru: '«Театр+» на фестивале Tashkent Flowers Fest 2026',
        excerpt_ru: 'Цветы, бабочка и садовод: история, созданная для главного весеннего фестиваля Ташкента.',
        category_ru: 'События',
        body_ru:
          'С 7 по 9 мая в столице прошел главный весенний фестиваль цветов Tashkent Flowers Fest 2026, который традиционно объединил жителей и гостей города на площади у Национальной библиотеки Узбекистана. На протяжении трех дней посетителей ждали масштабные цветочные экспозиции, гала-концерты, выступления фольклорных коллективов, ярмарка ремесленников и насыщенная культурно-развлекательная программа.\n\nТеатр+ стал частью этого яркого весеннего события, подарив зрителям атмосферную театральную постановку, созданную специально для фестиваля. На большой сцене артисты представили оригинальную историю, в которой ожили цветы, бабочка и садовод. Через пластику, актерскую игру и выразительные сценические образы зрители погрузились в сказочный мир, наполненный красотой природы, добротой и весенним настроением.\n\nПостановка была разработана с учетом тематики фестиваля и гармонично дополнила праздничную программу. Легкая, живая и красочная история одинаково увлекла как юных зрителей, так и взрослых, создавая особую атмосферу радости, вдохновения и единения с природой.\n\nУчастие в Tashkent Flowers Fest 2026 стало для Театра+ возможностью вновь встретиться со своей аудиторией в необычном формате открытой городской площадки и стать частью одного из самых красивых культурных событий весны. Благодарим организаторов фестиваля за приглашение и всех зрителей — за теплые аплодисменты, искренние улыбки и поддержку. До новых встреч на наших спектаклях и городских праздниках!',
        cover_alt_ru: 'Выступление Театр+ на Tashkent Flowers Fest 2026',
        gallery_alt_ru: 'Выступление Театр+ на Tashkent Flowers Fest 2026',
        author_ru: 'Редакция Театр+',
        photo_credit_ru: 'Фото: Театр+',
        title_en: 'Theater+ at Tashkent Flowers Fest 2026',
        excerpt_en: 'Flowers, a butterfly and a gardener: a story created for Tashkent’s spring flower festival.',
        category_en: 'Events',
        body_en:
          'From May 7 to 9, Tashkent Flowers Fest 2026 brought residents and visitors together on the square outside the National Library of Uzbekistan. Over three days, the capital’s spring flower festival offered large floral displays, gala concerts, folk performances, a craft fair and a full cultural programme.\n\nTheater+ joined the celebration with an atmospheric production created especially for the festival. On the main stage, the artists told an original story in which flowers, a butterfly and a gardener came to life. Movement, acting and expressive stage characters invited the audience into a fairy-tale world of natural beauty, kindness and spring.\n\nDeveloped around the festival’s theme, the production became part of its festive programme. The light-hearted, colourful story captivated children and adults alike, creating a shared sense of joy, inspiration and connection with nature.\n\nFor Theater+, Tashkent Flowers Fest 2026 was a chance to meet our audience in the unusual setting of an open-air city stage and take part in one of spring’s most beautiful cultural events. Thank you to the organisers for inviting us, and to every spectator for the applause, smiles and support. We look forward to seeing you at our performances and city celebrations!',
        cover_alt_en: 'Theater+ performing at Tashkent Flowers Fest 2026',
        gallery_alt_en: 'Theater+ performing at Tashkent Flowers Fest 2026',
        author_en: 'Theater+ editorial team',
        photo_credit_en: 'Photography: Theater+',
        title_uz: 'Teatr+ Tashkent Flowers Fest 2026 festivalida',
        excerpt_uz: 'Gullar, kapalak va bog‘bon: Toshkentning bahorgi gullar festivali uchun yaratilgan hikoya.',
        category_uz: 'Voqealar',
        body_uz:
          '7–9-may kunlari O‘zbekiston Milliy kutubxonasi oldidagi maydonda poytaxtning asosiy bahorgi gullar festivali — Tashkent Flowers Fest 2026 bo‘lib o‘tdi. Shahar aholisi va mehmonlarini birlashtirgan uch kunlik bayramda yirik gul kompozitsiyalari, gala-konsertlar, folklor jamoalari chiqishlari, hunarmandlar yarmarkasi va boy madaniy dastur taqdim etildi.\n\nTeatr+ ham ushbu yorqin bahor bayramiga qo‘shilib, festival uchun maxsus yaratilgan sahna asarini tomoshabinlarga namoyish etdi. Katta sahnada gullar, kapalak va bog‘bon jonlangan o‘ziga xos hikoya namoyish qilindi. Plastik harakatlar, aktyorlik mahorati va ifodali sahna obrazlari orqali tomoshabinlar tabiat go‘zalligi, mehr va bahor kayfiyatiga to‘la ertak olamiga sho‘ng‘idilar.\n\nFestival mavzusiga mos ishlab chiqilgan spektakl bayram dasturini uyg‘un ravishda to‘ldirdi. Yengil, jonli va rang-barang hikoya bolalarni ham, kattalarni ham birdek qiziqtirib, quvonch, ilhom va tabiat bilan hamohanglik muhitini yaratdi.\n\nTashkent Flowers Fest 2026 festivalidagi ishtirok Teatr+ uchun tomoshabinlar bilan ochiq shahar maydonida uchrashish va bahorning eng go‘zal madaniy tadbirlaridan biriga qo‘shilish imkonini berdi. Taklif uchun tashkilotchilarga, samimiy qarsaklar, tabassum va qo‘llab-quvvatlash uchun esa barcha tomoshabinlarga minnatdorchilik bildiramiz. Spektakllarimiz va shahar bayramlarida yana ko‘rishguncha!',
        cover_alt_uz: 'Teatr+ Tashkent Flowers Fest 2026 sahnasida',
        gallery_alt_uz: 'Teatr+ Tashkent Flowers Fest 2026 sahnasida',
        author_uz: 'Teatr+ tahririyati',
        photo_credit_uz: 'Suratlar: Teatr+',
      },
      {
        slug: 'international-childrens-day-2026',
        published_at: '2026-06-01 09:00:00.000Z',
        published: true,
        sample: false,
        cover_width: 1024,
        cover_height: 683,
        cover_url: 'https://teatrplus.uz/wp-content/uploads/2026/06/img_6663-1024x683.jpg',
        gallery_urls: [
          'https://teatrplus.uz/wp-content/uploads/2026/06/img_6670-1.png',
          'https://teatrplus.uz/wp-content/uploads/2026/06/img_6669-1.png',
          'https://teatrplus.uz/wp-content/uploads/2026/06/img_6668-1.png',
          'https://teatrplus.uz/wp-content/uploads/2026/06/img_6667-1.png',
          'https://teatrplus.uz/wp-content/uploads/2026/06/img_6665-1.png',
          'https://teatrplus.uz/wp-content/uploads/2026/06/img_6664-1.png',
          'https://teatrplus.uz/wp-content/uploads/2026/06/img_6663-1.png',
        ],
        title_ru: 'Международный день защиты детей',
        excerpt_ru: 'Благотворительный показ «Мастерской игрушек» — день, наполненный теплом, радостью и театром.',
        category_ru: 'Театр и город',
        body_ru:
          '31 мая 2026 года в преддверии Международного дня защиты детей, «Театр+» провёл специальный иммерсивный спектакль, на который были приглашены дети из детских домов и дети из малообеспеченных семей.\n\nТеатр — это пространство, где каждый ребёнок может прикоснуться к миру искусства, испытать искреннюю радость и стать частью настоящей сказки. Именно такую атмосферу создал благотворительный показ спектакля «Мастерская игрушек».\n\nВ этот день зрительный зал был наполнен искренними улыбками, смехом и яркими эмоциями. Юные зрители с большим интересом следили за развитием сюжета, сопереживали героям, радовались их успехам и с удовольствием погружались в волшебный мир, оживавший на сцене.\n\nВыражаем искреннюю благодарность Национальному агентству социальной защиты при Президенте Республики Узбекистан за поддержку данной инициативы и предоставленную возможность подарить детям незабываемый день, наполненный теплом, радостью и яркими впечатлениями.',
        cover_alt_ru: 'Благотворительный показ «Мастерской игрушек» в Театр+',
        gallery_alt_ru: 'Благотворительный показ «Мастерской игрушек» в Театр+',
        author_ru: 'Редакция Театр+',
        photo_credit_ru: 'Фото: Театр+',
        title_en: 'International Children’s Day',
        excerpt_en: 'A charity performance of The Toy Workshop: a day of warmth, joy and theater.',
        category_en: 'Theater and the city',
        body_en:
          'On May 31, 2026, ahead of International Children’s Day, Theater+ held a special immersive performance for children from children’s homes and low-income families.\n\nTheater is a place where every child can discover art, feel genuine joy and become part of a real fairy tale. That was the atmosphere created by this charity performance of The Toy Workshop.\n\nThe auditorium was filled with smiles, laughter and vivid emotions. The young audience followed the story closely, empathised with the characters, celebrated their successes and eagerly entered the magical world coming to life on stage.\n\nOur sincere thanks go to the National Agency for Social Protection under the President of the Republic of Uzbekistan for supporting this initiative and helping us give the children an unforgettable day full of warmth, joy and lasting impressions.',
        cover_alt_en: 'The Toy Workshop charity performance at Theater+',
        gallery_alt_en: 'The Toy Workshop charity performance at Theater+',
        author_en: 'Theater+ editorial team',
        photo_credit_en: 'Photography: Theater+',
        title_uz: 'Xalqaro bolalarni himoya qilish kuni',
        excerpt_uz: '«O‘yinchoqlar ustaxonasi» xayriya namoyishi — mehr, quvonch va teatrga to‘la kun.',
        category_uz: 'Teatr va shahar',
        body_uz:
          '2026-yil 31-may kuni, Xalqaro bolalarni himoya qilish kuni arafasida, Teatr+ maxsus immersiv spektakl namoyish etdi. Unga bolalar uylarida tarbiyalanayotgan va kam ta’minlangan oilalar farzandlari taklif qilindi.\n\nTeatr — har bir bola san’at olamiga yaqinlashishi, chin dildan quvonishi va haqiqiy ertakning bir qismiga aylanishi mumkin bo‘lgan makon. «O‘yinchoqlar ustaxonasi» spektaklining xayriya namoyishi aynan shunday muhit yaratdi.\n\nShu kuni tomosha zali samimiy tabassumlar, kulgi va yorqin his-tuyg‘ularga to‘ldi. Yosh tomoshabinlar voqealar rivojini katta qiziqish bilan kuzatdilar, qahramonlarga hamdard bo‘ldilar, ularning yutuqlaridan quvondilar va sahnada jonlanayotgan sehrli olamga zavq bilan sho‘ng‘idilar.\n\nUshbu tashabbusni qo‘llab-quvvatlagani va bolalarga mehr, quvonch hamda yorqin taassurotlarga boy unutilmas kun sovg‘a qilish imkonini bergani uchun O‘zbekiston Respublikasi Prezidenti huzuridagi Ijtimoiy himoya milliy agentligiga samimiy minnatdorchilik bildiramiz.',
        cover_alt_uz: 'Teatr+dagi «O‘yinchoqlar ustaxonasi» xayriya namoyishi',
        gallery_alt_uz: 'Teatr+dagi «O‘yinchoqlar ustaxonasi» xayriya namoyishi',
        author_uz: 'Teatr+ tahririyati',
        photo_credit_uz: 'Suratlar: Teatr+',
      },
      {
        slug: 'before-the-curtain',
        published_at: '2026-04-25 09:00:00.000Z',
        published: true,
        sample: true,
        cover_width: 1600,
        cover_height: 1067,
        cover_url: 'https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=max&w=1600&q=85',
        gallery_urls: [],
        title_ru: 'До первого звонка',
        excerpt_ru: 'О тишине перед выходом и маленьких деталях, из которых складывается спектакль.',
        category_ru: 'За кулисами',
        body_ru:
          'До открытия дверей у сцены свой ритм. Проверяют свет, расставляют реквизит, ещё раз проходят сложный переход. Зритель увидит цельную историю — и почти не заметит этой работы.\n\nНа репетиции важна не только большая сцена. Иногда всё держится на паузе, точном жесте или вовремя поданном предмете. Такие детали собирают по одной.\n\nПопробуйте на следующем спектакле заметить, как свет меняет пространство. Сцена остаётся той же, а место действия уже другое.',
        cover_alt_ru: 'Театральная сцена; иллюстративная фотография',
        gallery_alt_ru: 'Театральная сцена; иллюстративная фотография',
        author_ru: 'Редакция Театр+',
        photo_credit_ru: 'Unsplash',
        title_en: 'Before the first bell',
        excerpt_en: 'The quiet before an entrance, and the small details that bring a performance together.',
        category_en: 'Backstage',
        body_en:
          'Before the doors open, the stage has a rhythm of its own. Lights are checked, props placed and a difficult transition rehearsed again. The audience will see a complete story, with little sign of the work behind it.\n\nA rehearsal is not only about the big scenes. Sometimes everything depends on a pause, a precise gesture or a prop arriving on time. These details are assembled one at a time.\n\nAt your next performance, watch how light changes the space. The stage stays the same, but the story has already moved somewhere else.',
        cover_alt_en: 'A theater stage; illustrative stock photograph',
        gallery_alt_en: 'A theater stage; illustrative stock photograph',
        author_en: 'Theater+ editorial team',
        photo_credit_en: 'Unsplash',
        title_uz: 'Birinchi qo‘ng‘iroqqacha',
        excerpt_uz: 'Sahnaga chiqish oldidagi sukunat va spektaklni yaratadigan kichik tafsilotlar haqida.',
        category_uz: 'Sahna ortida',
        body_uz:
          'Eshiklar ochilishidan oldin sahnaning o‘z maromi bor. Chiroqlar tekshiriladi, rekvizit joylashtiriladi, murakkab o‘tish yana mashq qilinadi. Tomoshabin esa bu mehnatni deyarli sezmay, yaxlit hikoyani ko‘radi.\n\nRepetitsiyada faqat katta sahnalar muhim emas. Ba’zan hammasi bir pauza, aniq imo-ishora yoki o‘z vaqtida uzatilgan buyumga bog‘liq. Bunday tafsilotlar birma-bir yig‘iladi.\n\nKeyingi spektaklda yorug‘lik makonni qanday o‘zgartirishiga e’tibor bering. Sahna o‘sha-o‘sha, lekin voqea allaqachon boshqa joyga ko‘chgan.',
        cover_alt_uz: 'Teatr sahnasi; mavzuga oid namunaviy surat',
        gallery_alt_uz: 'Teatr sahnasi; mavzuga oid namunaviy surat',
        author_uz: 'Teatr+ tahririyati',
        photo_credit_uz: 'Unsplash',
      },
      {
        slug: 'first-visit-to-the-theater',
        published_at: '2026-04-12 09:00:00.000Z',
        published: true,
        sample: true,
        cover_width: 1600,
        cover_height: 1068,
        cover_url: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=max&w=1600&q=85',
        gallery_urls: [],
        title_ru: 'Первый поход в театр — вместе',
        excerpt_ru: 'Несколько простых идей для знакомства ребёнка со сценой.',
        category_ru: 'Зрителю',
        body_ru:
          'Первый поход в театр начинается ещё дома. Расскажите ребёнку, куда вы идёте: там будут актёры, музыка и история, которую вы увидите вместе. Не нужно заранее пересказывать весь сюжет.\n\nОставьте время на спокойный вход. Осмотреться, найти своё место, привыкнуть к новому пространству — это тоже часть знакомства с театром.\n\nПосле спектакля спросите, какой момент запомнился. Здесь нет правильных ответов. Иногда ребёнку важнее смешной звук или необычный свет, чем главный поворот истории.',
        cover_alt_ru: 'Зрительный зал; иллюстративная фотография',
        gallery_alt_ru: 'Зрительный зал; иллюстративная фотография',
        author_ru: 'Редакция Театр+',
        photo_credit_ru: 'Unsplash',
        title_en: 'A first theater visit, together',
        excerpt_en: 'A few simple ideas for introducing a child to the stage.',
        category_en: 'For audiences',
        body_en:
          'A first theater visit begins at home. Tell your child where you are going: there will be actors, music and a story to discover together. There is no need to explain the whole plot beforehand.\n\nLeave time for an unhurried arrival. Looking around, finding your seats and getting comfortable in a new space are all part of meeting the theater.\n\nAfterwards, ask which moment stayed with them. There are no right answers. A funny sound or an unusual light can matter more to a child than the story’s biggest turn.',
        cover_alt_en: 'An auditorium; illustrative stock photograph',
        gallery_alt_en: 'An auditorium; illustrative stock photograph',
        author_en: 'Theater+ editorial team',
        photo_credit_en: 'Unsplash',
        title_uz: 'Teatrga ilk bor — birga',
        excerpt_uz: 'Bolani sahna bilan tanishtirish uchun bir nechta oddiy fikr.',
        category_uz: 'Tomoshabinga',
        body_uz:
          'Teatrga birinchi tashrif uydayoq boshlanadi. Bolaga qayerga borayotganingizni ayting: u yerda aktyorlar, musiqa va birga ko‘radigan hikoya bo‘ladi. Syujetni oldindan to‘liq aytib berish shart emas.\n\nShoshilmasdan kirish uchun vaqt qoldiring. Atrofga qarash, joyingizni topish va yangi makonga ko‘nikish ham teatr bilan tanishishning bir qismi.\n\nSpektakldan keyin qaysi lahza esida qolganini so‘rang. Bu yerda to‘g‘ri javob yo‘q. Ba’zan kulgili tovush yoki noodatiy yorug‘lik bola uchun voqeaning asosiy burilishidan ham muhimroq bo‘ladi.',
        cover_alt_uz: 'Tomosha zali; mavzuga oid namunaviy surat',
        gallery_alt_uz: 'Tomosha zali; mavzuga oid namunaviy surat',
        author_uz: 'Teatr+ tahririyati',
        photo_credit_uz: 'Unsplash',
      },
      {
        slug: 'the-city-as-a-stage',
        published_at: '2026-03-28 09:00:00.000Z',
        published: true,
        sample: true,
        cover_width: 1600,
        cover_height: 1067,
        cover_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=max&w=1600&q=85',
        gallery_urls: [],
        title_ru: 'Когда город становится сценой',
        excerpt_ru: 'Как меняется встреча со зрителем под открытым небом.',
        category_ru: 'Заметки',
        body_ru:
          'Уличная сцена живёт по другим правилам. Здесь слышен город, меняется дневной свет, а зритель может остановиться случайно — и остаться до финала.\n\nАктёру приходится заново находить расстояние до публики. Крупный жест читается через площадь, а тихий эпизод требует особого внимания. Пространство становится участником истории.\n\nВ этом и есть радость городского спектакля: театр встречает людей посреди обычного дня. Для кого-то такая случайная встреча становится началом долгого знакомства.',
        cover_alt_ru: 'Открытая концертная площадка; иллюстративная фотография',
        gallery_alt_ru: 'Открытая концертная площадка; иллюстративная фотография',
        author_ru: 'Редакция Театр+',
        photo_credit_ru: 'Unsplash',
        title_en: 'When the city becomes a stage',
        excerpt_en: 'How an open-air setting changes the encounter with an audience.',
        category_en: 'Notes',
        body_en:
          'An outdoor stage follows different rules. The city is audible, daylight shifts, and a passer-by may stop by chance and stay until the end.\n\nThe performer has to find a new distance from the audience. A broad gesture carries across a square; a quiet moment calls for particular attention. The space itself becomes part of the story.\n\nThat is the pleasure of a city performance: theater meets people in the middle of an ordinary day. For someone, a chance encounter can be the beginning of a lasting connection.',
        cover_alt_en: 'An outdoor performance venue; illustrative stock photograph',
        gallery_alt_en: 'An outdoor performance venue; illustrative stock photograph',
        author_en: 'Theater+ editorial team',
        photo_credit_en: 'Unsplash',
        title_uz: 'Shahar sahnaga aylanganda',
        excerpt_uz: 'Ochiq osmon ostida tomoshabin bilan uchrashuv qanday o‘zgaradi.',
        category_uz: 'Qaydlar',
        body_uz:
          'Ko‘cha sahnasi boshqa qoidalarga bo‘ysunadi. Bu yerda shahar tovushlari eshitiladi, kunduzgi yorug‘lik o‘zgaradi, yo‘lovchi esa tasodifan to‘xtab, oxirigacha qolishi mumkin.\n\nAktyor tomoshabin bilan masofani yangidan topadi. Keng imo-ishora maydon bo‘ylab ko‘rinadi, sokin lahza esa alohida e’tibor talab qiladi. Makonning o‘zi hikoyaning ishtirokchisiga aylanadi.\n\nShahar spektaklining quvonchi ham shunda: teatr odamlarni oddiy kunning o‘rtasida uchratadi. Kimdir uchun shunday tasodifiy uchrashuv uzoq tanishuvning boshlanishi bo‘ladi.',
        cover_alt_uz: 'Ochiq konsert maydoni; mavzuga oid namunaviy surat',
        gallery_alt_uz: 'Ochiq konsert maydoni; mavzuga oid namunaviy surat',
        author_uz: 'Teatr+ tahririyati',
        photo_credit_uz: 'Unsplash',
      },
    ]
    const collection = app.findCollectionByNameOrId('t_blog_post')
    for (const post of posts) {
      if (app.findRecordsByFilter(collection, 'slug = {:slug}', '', 1, 0, { slug: post.slug }).length) continue
      const record = new Record(collection)
      const { cover_url, gallery_urls, ...content } = post
      record.load(content)
      record.set('cover', $filesystem.fileFromURL(cover_url, 45))
      record.set(
        'gallery',
        gallery_urls.map((url) => $filesystem.fileFromURL(url, 45)),
      )
      app.save(record)
    }
  },
  () => {
    // Seed posts may have been edited. Retain them and their photographs.
  },
)
