/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_3555510918',
          help: '',
          hidden: false,
          id: 'relation1773004765',
          maxSelect: 10,
          minSelect: 0,
          name: 'featured_plays',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_2759562249',
          help: '',
          hidden: false,
          id: 'relation3898856445',
          maxSelect: 0,
          minSelect: 0,
          name: 'about_block',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_2759562249',
          help: '',
          hidden: false,
          id: 'relation2804037359',
          maxSelect: 10,
          minSelect: 0,
          name: 'about_info_blocks',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_4060796684',
          help: '',
          hidden: false,
          id: 'relation1819994208',
          maxSelect: 0,
          minSelect: 0,
          name: 'about_mask',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_2759562249',
          help: '',
          hidden: false,
          id: 'relation3059665852',
          maxSelect: 0,
          minSelect: 0,
          name: 'instagram_block',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_1382429780',
          help: '',
          hidden: false,
          id: 'relation763647778',
          maxSelect: 0,
          minSelect: 0,
          name: 'instagram_button',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_2759562249',
          help: '',
          hidden: false,
          id: 'relation1054714857',
          maxSelect: 0,
          minSelect: 0,
          name: 'cta_block',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_1382429780',
          help: '',
          hidden: false,
          id: 'relation906850617',
          maxSelect: 0,
          minSelect: 0,
          name: 'cta_button',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_2759562249',
          help: '',
          hidden: false,
          id: 'relation1966515218',
          maxSelect: 0,
          minSelect: 0,
          name: 'bottom_block',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_1382429780',
          help: '',
          hidden: false,
          id: 'relation472494498',
          maxSelect: 0,
          minSelect: 0,
          name: 'bottom_button',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          help: '',
          hidden: false,
          id: 'file856700783',
          maxSelect: 0,
          maxSize: 0,
          mimeTypes: null,
          name: 'bottom_image',
          presentable: false,
          protected: false,
          required: false,
          system: false,
          thumbs: null,
          type: 'file',
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      id: 'pbc_2374593160',
      indexes: [],
      listRule: null,
      name: 't_page_home',
      system: false,
      type: 'base',
      updateRule: null,
      viewRule: null,
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_2374593160')

    return app.delete(collection)
  },
)
